import { StyleSheet } from "react-native";
import { typography, withTextStyle } from "@/styles/typography";
export const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
  },
  box: {
    width: 107,
    height: 34,
    backgroundColor: "#FFFFFF",
    borderColor: "#BDBDBD",
    borderRadius: 8,
    borderWidth: 1,
    marginRight: 8,
  },
  box2: {
    width: 107,
    height: 34,
    backgroundColor: "#FFFFFF",
    borderColor: "#BDBDBD",
    borderRadius: 8,
    borderWidth: 1,
    marginRight: 9,
  },
  box3: {
    width: 107,
    height: 34,
    backgroundColor: "#FFFFFF",
    borderColor: "#BDBDBD",
    borderRadius: 8,
    borderWidth: 1,
  },
  box4: {
    width: 63,
    height: 8,
    backgroundColor: "#45BC9E",
  },
  button: {
    width: 40,
    alignItems: "center",
    backgroundColor: "#FDC1AB",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 32,
  },
  button2: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 8,
    marginLeft: 32,
    marginRight: 8,
  },
  button3: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  button4: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#989898",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 9,
  },
  button5: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#989898",
    borderRadius: 8,
    paddingVertical: 10,
    marginRight: 8,
  },
  button6: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 10,
    marginRight: 9,
  },
  button7: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 9,
    marginRight: 8,
  },
  button8: {
    width: 130,
    alignItems: "center",
    backgroundColor: "#989898",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 65,
  },
  button9: {
    width: 33,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  button10: {
    width: 32,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button11: {
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginBottom: 4,
  },
  button12: {
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button13: {
    width: 23,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 10,
  },
  button14: {
    width: 22,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 10,
  },
  button15: {
    width: 24,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 20,
  },
  button16: {
    width: 32,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 7,
    marginRight: 10,
  },
  button17: {
    width: 32,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 10,
  },
  button18: {
    width: 28,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button19: {
    width: 29,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 4,
  },
  button20: {
    width: 29,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  button21: {
    width: 31,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button22: {
    width: 30,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  button23: {
    width: 30,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 16,
  },
  button24: {
    width: 31,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  button25: {
    width: 30,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button26: {
    width: 26,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 10,
    marginRight: 8,
  },
  button27: {
    width: 44,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  button28: {
    width: 62,
    alignItems: "center",
    backgroundColor: "#33C6FD",
    borderRadius: 8,
    paddingVertical: 16,
    marginRight: 16,
  },
  buttonColumn: {
    width: 54,
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    padding: 8,
    marginRight: 8,
  },
  buttonRow: {
    width: 72,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 10,
  },
  buttonRow2: {
    width: 73,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 10,
  },
  buttonRow3: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginBottom: 10,
  },
  buttonRow4: {
    width: 92,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 9,
  },
  buttonRow5: {
    width: 114,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  buttonRow6: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
  },
  buttonRow7: {
    width: 88,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginLeft: 32,
    marginRight: 8,
  },
  buttonRow8: {
    width: 297,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F9BE3C",
    borderRadius: 8,
    paddingVertical: 8,
  },
  mainContent: {
    width: 1440,
    flex: 1,
    backgroundColor: "#EFEFEF",
    borderWidth: 1,
    borderColor: "#EFEFEF",
  },
  column2: {
    marginTop: 2,
    marginBottom: 3,
  },
  column3: {
    width: 97,
    marginLeft: 32,
    marginRight: 16,
  },
  column4: {
    width: 35,
  },
  column5: {
    width: 229,
    alignItems: "center",
    marginRight: 16,
  },
  column6: {
    marginBottom: 16,
  },
  column7: {
    width: 244,
    marginRight: 16,
  },
  column8: {
    width: 133,
    marginRight: 16,
  },
  column9: {
    width: 99,
    marginRight: 16,
  },
  column10: {
    width: 216,
    alignItems: "center",
    marginRight: 309,
  },
  column11: {
    marginBottom: 11,
  },
  column12: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 8,
    marginBottom: 17,
    marginHorizontal: 8,
  },
  column13: {
    alignSelf: "flex-start",
    marginBottom: 32,
    marginLeft: 32,
  },
  image: {
    width: 38,
    height: 32,
    marginLeft: 32,
    marginRight: 8,
  },
  image2: {
    width: 40,
    height: 40,
    marginRight: 8,
  },
  image3: {
    width: 61,
    height: 39,
    marginRight: 8,
  },
  image4: {
    width: 39,
    height: 42,
    marginRight: 1134,
  },
  image5: {
    borderRadius: 8,
    width: 24,
    height: 24,
  },
  image6: {
    borderRadius: 8,
    width: 17,
    height: 16,
  },
  image7: {
    borderRadius: 8,
    width: 17,
    height: 17,
  },
  image8: {
    borderRadius: 8,
    width: 26,
    height: 31,
    marginBottom: 4,
  },
  image9: {
    borderRadius: 8,
    width: 9,
    height: 6,
  },
  image10: {
    borderRadius: 8,
    width: 19,
    height: 23,
  },
  image11: {
    borderRadius: 8,
    width: 18,
    height: 18,
  },
  image12: {
    borderRadius: 8,
    width: 9,
    height: 6,
    marginRight: 8,
  },
  image13: {
    borderRadius: 8,
    width: 7,
    height: 10,
  },
  image14: {
    borderRadius: 8,
    width: 6,
    height: 10,
  },
  image15: {
    borderRadius: 8,
    width: 8,
    height: 10,
  },
  image16: {
    borderRadius: 8,
    width: 16,
    height: 16,
  },
  image17: {
    borderRadius: 8,
    width: 16,
    height: 14,
  },
  image18: {
    borderRadius: 8,
    width: 12,
    height: 14,
  },
  image19: {
    borderRadius: 8,
    width: 13,
    height: 12,
  },
  image20: {
    borderRadius: 8,
    width: 15,
    height: 12,
  },
  image21: {
    borderRadius: 8,
    width: 14,
    height: 12,
  },
  image22: {
    width: 45,
    height: 32,
    marginRight: 7,
  },
  image23: {
    borderRadius: 8,
    width: 9,
    height: 6,
    marginRight: 7,
  },
  image24: {
    width: 46,
    height: 30,
    marginRight: 7,
  },
  image25: {
    width: 45,
    height: 32,
    marginRight: 8,
  },
  image26: {
    width: 44,
    height: 31,
  },
  image27: {
    width: 44,
    height: 31,
    marginBottom: 9,
  },
  image28: {
    borderRadius: 8,
    width: 15,
    height: 15,
    marginLeft: 8,
  },
  image29: {
    borderRadius: 8,
    width: 9,
    height: 6,
    marginRight: 6,
  },
  image30: {
    borderRadius: 8,
    width: 15,
    height: 15,
    marginLeft: 8,
    marginRight: 4,
  },
  image31: {
    borderRadius: 8,
    width: 12,
    height: 12,
    marginLeft: 8,
    marginRight: 10,
  },
  image32: {
    borderRadius: 8,
    width: 19,
    height: 14,
    marginRight: 10,
  },
  image33: {
    width: 11,
    height: 7,
  },
  image34: {
    width: 1176,
    height: 30,
    marginRight: 32,
  },
  image35: {
    width: 24,
    height: 17,
    marginRight: 8,
  },
  image36: {
    width: 87,
    height: 53,
    marginRight: 16,
  },
  image37: {
    borderRadius: 8,
    width: 30,
    height: 22,
  },
  image38: {
    borderRadius: 8,
    width: 16,
    height: 24,
    marginRight: 16,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    paddingVertical: 8,
  },
  row2: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    paddingVertical: 11,
  },
  row3: {
    width: 73,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 33,
  },
  row4: {
    flexDirection: "row",
    backgroundColor: "#FFFFFF",
    paddingVertical: 8,
  },
  row5: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
  },
  row6: {
    alignSelf: "flex-start",
    flexDirection: "row",
    marginBottom: 4,
  },
  row7: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 4,
  },
  row8: {
    alignSelf: "flex-start",
    flexDirection: "row",
    marginBottom: 8,
  },
  row9: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  row10: {
    flexDirection: "row",
    marginBottom: 10,
  },
  row11: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  row12: {
    flexDirection: "row",
    marginBottom: 8,
  },
  row13: {
    width: 96,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#EFEFEF",
    borderRadius: 8,
    paddingVertical: 8,
    marginRight: 8,
  },
  row14: {
    width: 29,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 8,
  },
  row15: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    marginHorizontal: 8,
  },
  row16: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  scrollView: {
    flexDirection: "row",
    paddingHorizontal: 8,
    marginBottom: 8,
  },
  scrollView2: {
    flexDirection: "row",
    paddingHorizontal: 8,
  },
  text: withTextStyle(typography.body, {
    color: "#292929",
  }),
  text2: withTextStyle(typography.caption, {
    color: "#292929",
    marginBottom: 4,
  }),
  text3: withTextStyle(typography.caption, {
    color: "#000000",
    textAlign: "center",
  }),
  text4: withTextStyle(typography.caption, {
    color: "#292929",
    marginLeft: 8,
    marginRight: 12,
  }),
  text5: withTextStyle(typography.caption, {
    color: "#292929",
    marginLeft: 8,
  }),
  text6: withTextStyle(typography.caption, {
    color: "#000000",
  }),
  text7: withTextStyle(typography.caption, {
    color: "#292929",
  }),
  text8: withTextStyle(typography.caption, {
    color: "#292929",
    marginRight: 6,
  }),
  text9: withTextStyle(typography.captionBold, {
    color: "#292929",
    textAlign: "center",
  }),
  text10: withTextStyle(typography.bodyBold, {
    color: "#292929",
    textAlign: "center",
  }),
  text11: withTextStyle(typography.headline, {
    color: "#903610",
    marginLeft: 16,
    flex: 1,
  }),
  view: {
    alignItems: "center",
  },
  view2: {
    width: 106,
    marginRight: 9,
  },
  view3: {
    width: 106,
  },
  view4: {
    width: 4,
    marginRight: 28,
  },
  view5: {
    width: 8,
    marginRight: 24,
  },
  view6: {
    width: 9,
    marginRight: 23,
  },
  view7: {
    width: 7,
    marginRight: 25,
  },
  view8: {
    width: 15,
    marginRight: 17,
  },
  view9: {
    width: 10,
    marginRight: 22,
  },
  view10: {
    width: 14,
    marginRight: 18,
  },
  view11: {
    width: 13,
    marginRight: 19,
  },
  view12: {
    width: 116,
    backgroundColor: "#FFFFFF",
    borderRadius: 8,
    paddingVertical: 23,
  },
  view13: {
    backgroundColor: "#989898",
    borderRadius: 4,
    marginHorizontal: 16,
  },
});
